//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.30 at 11:23:51 PM CET 
//


package com.example.model.naucni_rad;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.naucni_rad package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Referenca_QNAME = new QName("http://www.ftn.uns.ac.rs/naucni_rad", "Referenca");
    private final static QName _ObicanTekst_QNAME = new QName("http://www.ftn.uns.ac.rs/naucni_rad", "ObicanTekst");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.naucni_rad
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Revizija }
     * 
     */
    public Revizija createRevizija() {
        return new Revizija();
    }

    /**
     * Create an instance of {@link Lista }
     * 
     */
    public Lista createLista() {
        return new Lista();
    }

    /**
     * Create an instance of {@link Tekst }
     * 
     */
    public Tekst createTekst() {
        return new Tekst();
    }

    /**
     * Create an instance of {@link Poglavlje }
     * 
     */
    public Poglavlje createPoglavlje() {
        return new Poglavlje();
    }

    /**
     * Create an instance of {@link Poglavlje.Paragraf }
     * 
     */
    public Poglavlje.Paragraf createPoglavljeParagraf() {
        return new Poglavlje.Paragraf();
    }

    /**
     * Create an instance of {@link Poglavlje.Paragraf.Tabela }
     * 
     */
    public Poglavlje.Paragraf.Tabela createPoglavljeParagrafTabela() {
        return new Poglavlje.Paragraf.Tabela();
    }

    /**
     * Create an instance of {@link NaucniRad }
     * 
     */
    public NaucniRad createNaucniRad() {
        return new NaucniRad();
    }

    /**
     * Create an instance of {@link Revizija.Sadrzaj }
     * 
     */
    public Revizija.Sadrzaj createRevizijaSadrzaj() {
        return new Revizija.Sadrzaj();
    }

    /**
     * Create an instance of {@link Lista.Stavke }
     * 
     */
    public Lista.Stavke createListaStavke() {
        return new Lista.Stavke();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link Tekst.Highlight }
     * 
     */
    public Tekst.Highlight createTekstHighlight() {
        return new Tekst.Highlight();
    }

    /**
     * Create an instance of {@link Tekst.Citat }
     * 
     */
    public Tekst.Citat createTekstCitat() {
        return new Tekst.Citat();
    }

    /**
     * Create an instance of {@link Tekst.Link }
     * 
     */
    public Tekst.Link createTekstLink() {
        return new Tekst.Link();
    }

    /**
     * Create an instance of {@link Tekst.MatematickaForma }
     * 
     */
    public Tekst.MatematickaForma createTekstMatematickaForma() {
        return new Tekst.MatematickaForma();
    }

    /**
     * Create an instance of {@link Tekst.Footnote }
     * 
     */
    public Tekst.Footnote createTekstFootnote() {
        return new Tekst.Footnote();
    }

    /**
     * Create an instance of {@link Izdavac }
     * 
     */
    public Izdavac createIzdavac() {
        return new Izdavac();
    }

    /**
     * Create an instance of {@link TNeStrukturiranAbstakt }
     * 
     */
    public TNeStrukturiranAbstakt createTNeStrukturiranAbstakt() {
        return new TNeStrukturiranAbstakt();
    }

    /**
     * Create an instance of {@link TNaucniRad }
     * 
     */
    public TNaucniRad createTNaucniRad() {
        return new TNaucniRad();
    }

    /**
     * Create an instance of {@link TStrukturiranAbstrakt }
     * 
     */
    public TStrukturiranAbstrakt createTStrukturiranAbstrakt() {
        return new TStrukturiranAbstrakt();
    }

    /**
     * Create an instance of {@link TClanak }
     * 
     */
    public TClanak createTClanak() {
        return new TClanak();
    }

    /**
     * Create an instance of {@link TRecenzija }
     * 
     */
    public TRecenzija createTRecenzija() {
        return new TRecenzija();
    }

    /**
     * Create an instance of {@link TPoglavlja }
     * 
     */
    public TPoglavlja createTPoglavlja() {
        return new TPoglavlja();
    }

    /**
     * Create an instance of {@link TKnjiga }
     * 
     */
    public TKnjiga createTKnjiga() {
        return new TKnjiga();
    }

    /**
     * Create an instance of {@link TWebSajt }
     * 
     */
    public TWebSajt createTWebSajt() {
        return new TWebSajt();
    }

    /**
     * Create an instance of {@link Poglavlje.Paragraf.Figura }
     * 
     */
    public Poglavlje.Paragraf.Figura createPoglavljeParagrafFigura() {
        return new Poglavlje.Paragraf.Figura();
    }

    /**
     * Create an instance of {@link Poglavlje.Paragraf.Tabela.Red }
     * 
     */
    public Poglavlje.Paragraf.Tabela.Red createPoglavljeParagrafTabelaRed() {
        return new Poglavlje.Paragraf.Tabela.Red();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/naucni_rad", name = "Referenca")
    @XmlIDREF
    public JAXBElement<Object> createReferenca(Object value) {
        return new JAXBElement<Object>(_Referenca_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/naucni_rad", name = "ObicanTekst")
    public JAXBElement<TTekst> createObicanTekst(TTekst value) {
        return new JAXBElement<TTekst>(_ObicanTekst_QNAME, TTekst.class, null, value);
    }

}
