//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.01 at 02:58:46 PM CET 
//


package com.example.model.naucni_rad;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TNaucniRad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TNaucniRad">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ftn.uns.ac.rs/naucni_rad}TReferenca">
 *       &lt;sequence>
 *         &lt;element name="Naucni_rad" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Strana">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNaucniRad", propOrder = {
    "naucniRad"
})
public class TNaucniRad
    extends TReferenca
{

    @XmlElement(name = "Naucni_rad", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object naucniRad;
    @XmlAttribute(name = "Strana")
    protected BigInteger strana;

    /**
     * Gets the value of the naucniRad property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNaucniRad() {
        return naucniRad;
    }

    /**
     * Sets the value of the naucniRad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNaucniRad(Object value) {
        this.naucniRad = value;
    }

    /**
     * Gets the value of the strana property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStrana() {
        return strana;
    }

    /**
     * Sets the value of the strana property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStrana(BigInteger value) {
        this.strana = value;
    }

}
