//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.30 at 11:23:51 PM CET 
//


package com.example.model.naucni_rad;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.example.model.recenzija.Recenzija;


/**
 * <p>Java class for TRecenzija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRecenzija">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ftn.uns.ac.rs/naucni_rad}TReferenca">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/recenzija}Recenzija"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRecenzija", propOrder = {
    "recenzija"
})
public class TRecenzija
    extends TReferenca
{

    @XmlElement(name = "Recenzija", namespace = "http://www.ftn.uns.ac.rs/recenzija", required = true)
    protected Recenzija recenzija;

    /**
     * Gets the value of the recenzija property.
     * 
     * @return
     *     possible object is
     *     {@link Recenzija }
     *     
     */
    public Recenzija getRecenzija() {
        return recenzija;
    }

    /**
     * Sets the value of the recenzija property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recenzija }
     *     
     */
    public void setRecenzija(Recenzija value) {
        this.recenzija = value;
    }

}
